<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="18" hostname="DESKTOP-K0SFL7M" failures="1" tests="2" name="Default test" time="162.024" errors="0" timestamp="2021-06-30T14:28:36 PKT">
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="NavigateSalmonella" time="49.078"/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="TestFilter" time="48.768">
    <failure type="java.lang.Exception" message="java.lang.AssertionError: expected [1] but found [0]">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [1] but found [0]
at Test.Ancera.Reports.SalmonellaLog.TestFilter(SalmonellaLog.java:797)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [1] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at Test.Ancera.Reports.SalmonellaLog.TestFilter(SalmonellaLog.java:788)
... 28 more
]]>
    </failure>
  </testcase> <!-- TestFilter -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="RunAPI" time="0.0">
    <ignored/>
  </testcase> <!-- RunAPI -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="DateFilter" time="0.0">
    <ignored/>
  </testcase> <!-- DateFilter -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="AuditLog1" time="0.0">
    <ignored/>
  </testcase> <!-- AuditLog1 -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="TestFilters" time="0.0">
    <ignored/>
  </testcase> <!-- TestFilters -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="RowsPerPage" time="0.0">
    <ignored/>
  </testcase> <!-- RowsPerPage -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="PNGExport" time="0.0">
    <ignored/>
  </testcase> <!-- PNGExport -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="FieldAccessDrag" time="0.0">
    <ignored/>
  </testcase> <!-- FieldAccessDrag -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="ResetFilter" time="0.0">
    <ignored/>
  </testcase> <!-- ResetFilter -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="FieldAccessUnview" time="0.0">
    <ignored/>
  </testcase> <!-- FieldAccessUnview -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="TemplateExport" time="0.0">
    <ignored/>
  </testcase> <!-- TemplateExport -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="Pagination" time="0.0">
    <ignored/>
  </testcase> <!-- Pagination -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="FieldAccessView" time="0.0">
    <ignored/>
  </testcase> <!-- FieldAccessView -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="AuditLog" time="0.0">
    <ignored/>
  </testcase> <!-- AuditLog -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="DateLockFilter" time="0.0">
    <ignored/>
  </testcase> <!-- DateLockFilter -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="SalmonellaLock" time="0.0">
    <ignored/>
  </testcase> <!-- SalmonellaLock -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="CSVExport" time="0.0">
    <ignored/>
  </testcase> <!-- CSVExport -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="Sorting" time="0.0">
    <ignored/>
  </testcase> <!-- Sorting -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="EnterDate" time="0.0">
    <ignored/>
  </testcase> <!-- EnterDate -->
</testsuite> <!-- Default test -->
