<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="13" hostname="DESKTOP-K0SFL7M" failures="2" tests="5" name="Default test" time="82.865" errors="0" timestamp="2021-07-12T14:34:15 PKT">
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="NavigateSalmonella" time="25.443"/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="PNGExport" time="13.999">
    <failure type="java.lang.Exception" message="java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [true] but found [false]
at Test.Ancera.Reports.SalmonellaLog.PNGExport(SalmonellaLog.java:1549)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test.Ancera.Reports.SalmonellaLog.PNGExport(SalmonellaLog.java:1540)
... 28 more
]]>
    </failure>
  </testcase> <!-- PNGExport -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="CSVExport" time="8.793"/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="CSVAuditExport" time="8.67">
    <failure type="java.lang.Exception" message="java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [true] but found [false]
at Test.Ancera.Reports.SalmonellaLog.CSVAuditExport(SalmonellaLog.java:1661)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test.Ancera.Reports.SalmonellaLog.CSVAuditExport(SalmonellaLog.java:1652)
... 28 more
]]>
    </failure>
  </testcase> <!-- CSVAuditExport -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="TemplateExport" time="5.675"/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="RunAPI" time="0.0">
    <ignored/>
  </testcase> <!-- RunAPI -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="DateFilter" time="0.0">
    <ignored/>
  </testcase> <!-- DateFilter -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="AuditLog1" time="0.0">
    <ignored/>
  </testcase> <!-- AuditLog1 -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="RowsPerPage" time="0.0">
    <ignored/>
  </testcase> <!-- RowsPerPage -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="FieldAccessUnview" time="0.0">
    <ignored/>
  </testcase> <!-- FieldAccessUnview -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="Pagination" time="0.0">
    <ignored/>
  </testcase> <!-- Pagination -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="FieldAccessView" time="0.0">
    <ignored/>
  </testcase> <!-- FieldAccessView -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="DateLockFilter" time="0.0">
    <ignored/>
  </testcase> <!-- DateLockFilter -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="AuditLog" time="0.0">
    <ignored/>
  </testcase> <!-- AuditLog -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="wildcard" time="0.0">
    <ignored/>
  </testcase> <!-- wildcard -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="SalmonellaLock" time="0.0">
    <ignored/>
  </testcase> <!-- SalmonellaLock -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="TestFilter" time="0.0">
    <ignored/>
  </testcase> <!-- TestFilter -->
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="Sorting" time="0.0">
    <ignored/>
  </testcase> <!-- Sorting -->
</testsuite> <!-- Default test -->
