<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K0SFL7M" failures="0" tests="28" name="Test.Ancera.Administration.OrganizationManagement" time="1222.476" errors="3" timestamp="2022-08-10T20:32:08 PKT" skipped="2">
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="Navigate" time="14.035"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="OpenClosePopup" time="3.614"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="MandatoryFieldCheck" time="98.942"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="ResetButton" time="1.394"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="testInvalidEmail" time="19.371"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="CreateOrganization" time="14.607"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="VerifyCreatedOrganization" time="30.674"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="UpdateOrganization" time="28.746"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="VerifyUpdateOrganization" time="3.021"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="OrganizationSitesHierarchyCheck" time="20.844">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;css selector&quot;,&quot;selector&quot;:&quot;div .ng-dropdown-panel-items&quot;}
  (Session info: chrome=103.0.5060.134)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: &#039;4.1.2&#039;, revision: &#039;9a5a329c5a&#039;
System info: host: &#039;DESKTOP-K0SFL7M&#039;, ip: &#039;192.168.56.1&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;15.0.2&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [5de7173e78f141e7b73a48cdf1cf7ca4, findElement {using=css selector, value=div .ng-dropdown-panel-items}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.134, chrome: {chromedriverVersion: 103.0.5060.134 (8ec6fce403b..., userDataDir: C:\Users\User\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:55889}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:55889/devtoo..., se:cdpVersion: 103.0.5060.134, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 5de7173e78f141e7b73a48cdf1cf7ca4" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"div .ng-dropdown-panel-items"}
  (Session info: chrome=103.0.5060.134)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'DESKTOP-K0SFL7M', ip: '192.168.56.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [5de7173e78f141e7b73a48cdf1cf7ca4, findElement {using=css selector, value=div .ng-dropdown-panel-items}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.134, chrome: {chromedriverVersion: 103.0.5060.134 (8ec6fce403b..., userDataDir: C:\Users\User\AppData\Local...}, goog:chromeOptions: {debuggerAddress: localhost:55889}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:55889/devtoo..., se:cdpVersion: 103.0.5060.134, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 5de7173e78f141e7b73a48cdf1cf7ca4
at jdk.internal.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:558)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:382)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:374)
at Test.Ancera.Administration.OrganizationManagement.OrganizationSitesHierarchyCheck(OrganizationManagement.java:551)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- OrganizationSitesHierarchyCheck -->
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="OrganizationSiteMandatoryCheck" time="12.546"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="SiteResetButton" time="1.912"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="CreateOrganizationSite" time="22.074"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="UpdateOrganizationSites" time="17.726">
    <error message="java.lang.AssertionError: The following asserts failed:
	Latitude did not autofilled expected [40.712775] but found [41],
	Longitude did not autofilled expected [-74.005973] but found [-74]" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: The following asserts failed:
Latitude did not autofilled expected [40.712775] but found [41],
Longitude did not autofilled expected [-74.005973] but found [-74]
at Test.Ancera.Administration.OrganizationManagement.UpdateOrganizationSites(OrganizationManagement.java:946)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
Latitude did not autofilled expected [40.712775] but found [41],
Longitude did not autofilled expected [-74.005973] but found [-74]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Test.Ancera.Administration.OrganizationManagement.UpdateOrganizationSites(OrganizationManagement.java:938)
... 28 more
]]>
    </error>
  </testcase> <!-- UpdateOrganizationSites -->
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="VerifyUpdateOrganizationSites" time="12.992"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="DeleteOrganizationSites" time="4.281"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="BulkUploadEmpty" time="17.343"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="BulkUpload" time="255.399"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="InActiveOrganization" time="18.162"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="VerifyInActiveOrganization" time="20.369"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="DeleteOrganization" time="43.969">
    <error message="java.lang.AssertionError: The following asserts failed:
	did not expect [20] but found [20]" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: The following asserts failed:
did not expect [20] but found [20]
at Test.Ancera.Administration.OrganizationManagement.DeleteOrganization(OrganizationManagement.java:1421)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: The following asserts failed:
did not expect [20] but found [20]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Test.Ancera.Administration.OrganizationManagement.DeleteOrganization(OrganizationManagement.java:1413)
... 28 more
]]>
    </error>
  </testcase> <!-- DeleteOrganization -->
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="TestFilter" time="137.696"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="Wildcard" time="227.502"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="Lock" time="166.578"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="Sorting" time="7.180"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="CSVExport" time="21.499"/>
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="AssignAgreement">
    <skipped/>
  </testcase> <!-- AssignAgreement -->
  <system-out/>
  <testcase classname="Test.Ancera.Administration.OrganizationManagement" name="TestFilterPractice">
    <skipped/>
  </testcase> <!-- TestFilterPractice -->
  <system-out/>
</testsuite> <!-- Test.Ancera.Administration.OrganizationManagement -->
