<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K0SFL7M" failures="0" tests="18" name="Test.Ancera.Reports.SalmonellaLog" time="3209.905" errors="1" timestamp="2022-02-14T19:01:09 PKT" skipped="3">
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="NavigateSalmonella" time="41.473"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="DateFilter" time="76.957"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="DateLockFilter" time="32.641"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="TestFilter" time="393.739"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="SiteName" time="33.634"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="SalmonellaLock" time="641.724"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="Pagination" time="21.014"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="RowsPerPage" time="59.409"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="Sorting" time="3.083"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="AllignmentTest" time="0.461"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="FieldAccessResetDefault" time="9.796"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="PNGExport" time="41.286"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="CSVExport" time="1825.616"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="CSVAuditExport" time="18.321"/>
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="TemplateExport" time="10.751">
    <error message="java.lang.AssertionError: expected [Sample Metadata Upload Template.xlsx] but found [Sample Metadata Upload Template (3).xlsx]" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: java.lang.AssertionError: expected [Sample Metadata Upload Template.xlsx] but found [Sample Metadata Upload Template (3).xlsx]
at Test.Ancera.Reports.SalmonellaLog.TemplateExport(SalmonellaLog.java:1747)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [Sample Metadata Upload Template.xlsx] but found [Sample Metadata Upload Template (3).xlsx]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test.Ancera.Reports.SalmonellaLog.TemplateExport(SalmonellaLog.java:1735)
... 28 more
]]>
    </error>
  </testcase> <!-- TemplateExport -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="FieldAccess">
    <skipped/>
  </testcase> <!-- FieldAccess -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="wildcard">
    <skipped/>
  </testcase> <!-- wildcard -->
  <system-out/>
  <testcase classname="Test.Ancera.Reports.SalmonellaLog" name="Contexual">
    <skipped/>
  </testcase> <!-- Contexual -->
  <system-out/>
</testsuite> <!-- Test.Ancera.Reports.SalmonellaLog -->
